name: Metrics

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "metrics"
  cancel-in-progress: false

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest Go workflow run number
        id: latest-go-run
        run: |
          gh run list \
            --repo '${{ github.repository }}' \
            --workflow 'Go' \
            --branch main \
            --status completed \
            --limit 1 \
            --json databaseId \
            --jq '"run-id=\(.[0].databaseId)"' \
          | tee -a "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: github_exporter
          github-token: ${{ secrets.GH_TOKEN }}
          run-id: ${{ steps.latest-go-run.outputs.run-id }}

      - name: Fix permissions
        run: |
          chmod +x ./github_exporter

      - name: Connect to Tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions

      - name: Push metrics to gateway
        run: |
          ./github_exporter generate --pushgateway-retries=3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_EXPORTER_PUSHGATEWAY_URL: ${{ secrets.GH_EXPORTER_PUSHGATEWAY_URL }}
