name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "metrics"
  cancel-in-progress: false

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          go build

      - name: Connect to Tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions

      - name: Push metrics to gateway
        run: |
          ./github_exporter generate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_EXPORTER_OUTPUT: "-"
          GITHUB_EXPORTER_PUSHGATEWAY_URL: ${{ secrets.GH_EXPORTER_PUSHGATEWAY_URL }}
